ROOT=`pwd`
PROJ_DIR=$ROOT/projects/vs2012_win32
BUILD_DIR=$ROOT/builds/vs2012_win32
LIB_DIR=$ROOT/builds/vs2012_win32/libs
BIN_DIR=$ROOT/builds/vs2012_win32/bins
rm -rf $PROJ_DIR
mkdir -p $PROJ_DIR
mkdir -p $LIB_DIR
mkdir -p $BIN_DIR
pushd $PROJ_DIR
cmake \
-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=$LIB_DIR \
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=$LIB_DIR \
-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=$BIN_DIR \
-DNIMBLE_TARGET_WIN32=ON \
-DNIMBLE_VISUALSTUDIO_2012=ON \
-G "Visual Studio 12" $ROOT
popd